register = { 'w'..'z'}
number = { "-"? ~ ASCII_DIGIT+ }

inp = { "inp" ~ register }
add = { "add" ~ register ~ (register | number) }
mul = { "mul" ~ register ~ (register | number) }
div = { "div" ~ register ~ (register | number) }
modulo = { "mod" ~ register ~ (register | number) }
eql = { "eql" ~ register ~ (register | number) }

instruction = { (inp | add | mul | div | modulo | eql) }

WHITESPACE = _{" "}